### ISSUE TITLE
[Tracker] Features to be implemented

### ISSUE THREAD

**Issue by greybaron** [greybaron/campus-unbloat#11]
- Exam modal:
  - [x] #33
  - [x] #32
  - [x] #38
-  Backend:
    - [x] #29
    - [x] #30
    - [x] #31
    - [x] transfer the hsl calc logic from frontend/calender into the backend (originally from #40) 
- Mensa tile/modal:
  - [x] #34
  - [x] #51
  - [x] Increase API day caching to something reasonable like a week ahead (currently 3 days)
- Basic info tile:
  - [x] #14
  - [x] #12
  - [x] #13
- Calendar tile/modal:
  - [x] #41
  - [x] #61
    - store the time of the last update in LocalStorage and only request the calendar if some time passed
  - [x] #40
     -alternatively: implement API-side checks so that title->color hasher cannot produce very light colors
  - [x] #46
  - [x] #47
  - [x] #48
  - [x] #77
  - [x] #76 
  - [x] #80
  - [x] #66
    - [x] Add API endpoint
- [x] #39 
- [x] #53
- 'Document' tile to download pdf documents
  - API endpoint feasibility needs to be checked first
